/* City Survey Demo — responsibility: load JSON/GeoJSON, render charts/map,
   geocode submitted cities, and send updated datasets to the write service. */
const JSON_URL="data/testData.json", GEOJSON_URL="data/testData.geojson";
// Set this after deploying the Worker. Blank = read-only demo.
const WRITE_API_URL="";
let data={respondents:[]}, geo={type:"FeatureCollection",features:[]}, genderChart, scatterChart, map, layer;
addEventListener("DOMContentLoaded",init);
async function init(){map=L.map("map").setView([39.5,-98.35],4);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);try{await load();render();document.querySelector("#status").textContent="Data loaded"}catch(e){document.querySelector("#status").textContent="Load error";console.error(e)}document.querySelector("#form").addEventListener("submit",submit)}
async function load(){const [a,b]=await Promise.all([fetch(JSON_URL,{cache:"no-store"}),fetch(GEOJSON_URL,{cache:"no-store"})]);if(!a.ok||!b.ok)throw Error("Could not load the data files.");data=await a.json();geo=await b.json()}
function render(){renderGender();renderScatter();renderMap();document.querySelector("#count").textContent=`${data.respondents.length} respondent${data.respondents.length===1?"":"s"}`}
function renderGender(){let m=data.respondents.filter(d=>d.gender==="M").length,f=data.respondents.filter(d=>d.gender==="F").length,t=data.respondents.length||1;if(genderChart)genderChart.destroy();genderChart=new Chart(document.querySelector("#genderChart"),{type:"bar",data:{labels:["Male","Female"],datasets:[{data:[m/t*100,f/t*100],backgroundColor:["#4778b8","#d58b43"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw.toFixed(1)}%`}}},scales:{y:{min:0,max:100,ticks:{callback:v=>v+"%"},title:{display:true,text:"Percent"}}}}})}
function renderScatter(){const pts=data.respondents.map(r=>({x:+r.favoriteNumber100,y:+r.favoriteNumber10,c:cssColor(r.favoriteColor)?r.favoriteColor:"#667085",r}));if(scatterChart)scatterChart.destroy();scatterChart=new Chart(document.querySelector("#scatterChart"),{type:"scatter",data:{datasets:[{data:pts,pointRadius:7,pointHoverRadius:10,pointBackgroundColor:c=>c.raw?.c||"#667085",pointBorderColor:"#344054"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw.r.favoriteColor}: (${c.raw.x}, ${c.raw.y})`}}},scales:{x:{min:0,max:100,title:{display:true,text:"Favorite number (0–100)"}},y:{min:0,max:10,title:{display:true,text:"Favorite number (0–10)"}}}}})}
function renderMap(){if(layer)map.removeLayer(layer);layer=L.geoJSON(geo,{pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,fillColor:cssColor(f.properties?.favoriteColor)?f.properties.favoriteColor:"#2457a6",color:"#344054",weight:1,fillOpacity:.85}),onEachFeature:(f,l)=>{const p=f.properties||{};l.bindPopup(`<b>${esc(p.city)}, ${esc(p.state)}</b><br>Gender: ${esc(p.gender)}<br>Color: ${esc(p.favoriteColor)}<br>Numbers: ${esc(p.favoriteNumber10)}, ${esc(p.favoriteNumber100)}`)}}).addTo(map);if(layer.getBounds().isValid())map.fitBounds(layer.getBounds().pad(.15))}
async function submit(e){e.preventDefault();const btn=document.querySelector("#submit");btn.disabled=true;msg("Geocoding city…");try{const r={id:`r-${Date.now()}`,gender:gender.value,favoriteNumber10:+n10.value,favoriteNumber100:+n100.value,favoriteColor:color.value.trim(),city:city.value.trim(),state:state.value.trim(),submittedAt:new Date().toISOString()};const g=await geocode(r.city,r.state);if(!g)throw Error("City/state not found.");r.latitude=g.lat;r.longitude=g.lon;r.displayName=g.name;data.respondents.push(r);geo.features.push({type:"Feature",properties:{...r},geometry:{type:"Point",coordinates:[r.longitude,r.latitude]}});render();await save();e.target.reset();msg(`Saved ${r.city}, ${r.state}.`)}catch(err){console.error(err);msg(err.message,true)}finally{btn.disabled=false}}
async function geocode(cityName,stateName){const q=new URLSearchParams({city:cityName,state:stateName,country:"United States",format:"jsonv2",limit:"1"});const r=await fetch(`https://nominatim.openstreetmap.org/search?${q}`);if(!r.ok)throw Error("Geocoding service unavailable.");const a=await r.json();return a[0]?{lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name}:null}
async function save(){if(!WRITE_API_URL)throw Error("Read-only demo: set WRITE_API_URL in app.js to enable writing.");const r=await fetch(`${WRITE_API_URL}/write`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({jsonData:data,geojsonData:geo})});if(!r.ok)throw Error(`Save failed: ${await r.text()}`);document.querySelector("#status").textContent="Saved to GitHub"}
function cssColor(v){const s=new Option().style;s.color=v;return s.color!==""}function msg(t,bad=false){const e=document.querySelector("#formStatus");e.textContent=t;e.style.color=bad?"#b42318":"#475467"}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
